#!/usr/bin/env python

from os.path import join, expanduser
from pyjsonrpc import HttpClient
import sys

currency = "CBT"

def get_config():
    lines = open(join(expanduser("~"), ".teleport", "teleport.conf")).readlines()
    def split(string):
        return string.split("=", 1) if "=" in string else ("", "")
    return {key: value.strip() for key, value in map(split, lines)}

def client():
    url = "http://localhost:" + get_config()[currency + '-rpcport']
    return HttpClient(url=url)

def getbalance(user):
    print client().balance(user)

def send(payer, payee, amount):
    print client().send(payer, payee, amount)

def help():
    print \
"""
Usage: %s (balance <user> | send <payer> <payee> <amount>)
""" % sys.argv[0]


def main(argv):
    if len(argv) == 1:
        return help()
    command, params = argv[1], argv[2:]
    if command == "balance":
        user = params[0]
        return getbalance(user)
    if command == "send":
        payer, payee, amount = params
        return send(payer, payee, amount)
    return help()


if __name__ == '__main__':
    main(sys.argv)
